baseURL = "/"
languageCode = "en-us"
title = "endomer+py"
Paginate = 1000
googleAnalytics = ""
theme = "showcase-hugo-theme"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

[params]
  author = "endomer+py"
  description = "Página web principal del proyecto Encuestas Dominicanas en R y Python (endomer+py)"
  message = "Es un proyecto que busca proveer herramientas útiles para trabajar con las bases de datos de encuestas dominicanas en R y/o Python. El objetivo principal es el de proveer la mayor cantidad de información posible relacionada con las encuestas. Así como funciones para calcular los principales indicadores que regularmente se calculan con dicha encuesta. Todos los paquetes del ecosistema endomer te permiten utilizar etiquetas de datos en R. Además de que puedes visualizar estas etiquetas (diccionario) de forma interactiva. Mira en cada uno de los paquetes para ver que más se ofrece."
  hideAutoMenu = false

[social]
  twitter = "https://twitter.com/search?q=%23endomer+py&src=typed_query"
  github = "https://github.com/endomer-py"
